# Generated by Django 4.2.3 on 2023-07-27 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('data_cadastro', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'autor',
                'db_table_comment': 'Cadastro dos Autores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_cadastro', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'categoria',
                'db_table_comment': 'categorias de livro',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Editora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_cadastro', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'editora',
                'db_table_comment': 'Cadastro de editoras',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=150)),
                ('data_lancamento', models.DateField(blank=True, null=True)),
                ('isbn', models.CharField(blank=True, db_column='ISBN', max_length=13, null=True)),
                ('capa', models.TextField(blank=True, null=True)),
                ('data_compra', models.DateField(blank=True, null=True)),
                ('avaliacao', models.CharField(blank=True, choices=[('1', 'Pessimo'), ('2', 'Ruim'), ('3', 'Regular'), ('4', 'Bom'), ('5', 'Otimo')], max_length=1, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_cadastro', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'livro',
                'db_table_comment': 'cadastro de livros',
                'managed': False,
            },
        ),
    ]
